cp /usr/lib/arm-linux-gnueabihf/libarmmem-v8l.so ./lib/
cp /lib/arm-linux-gnueabihf/libSDL2-2.0.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libSDL2_ttf-2.0.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libgif.so.7 ./lib/
cp /lib/arm-linux-gnueabihf/libc.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libasound.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libm.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libdl.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libpulse.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libX11.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libXext.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libXcursor.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXinerama.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXi.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libXrandr.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libXss.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXxf86vm.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libdrm.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libgbm.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libwayland-egl.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libwayland-client.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libwayland-cursor.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libxkbcommon.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libpthread.so.0 ./lib/

cp /lib/arm-linux-gnueabihf/libfreetype.so.6 ./lib/
cp /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsecommon-14.2.so ./lib/
cp /lib/arm-linux-gnueabihf/libdbus-1.so.3 ./lib/
cp /lib/arm-linux-gnueabihf/libxcb.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXrender.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXfixes.so.3 ./lib/
cp /lib/arm-linux-gnueabihf/libwayland-server.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libexpat.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libffi.so.7 ./lib/
cp /lib/arm-linux-gnueabihf/libpng16.so.16 ./lib/
cp /lib/arm-linux-gnueabihf/libz.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libbrotlidec.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libsystemd.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libwrap.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libsndfile.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libasyncns.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/librt.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libXau.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libXdmcp.so.6 ./lib/
cp /lib/arm-linux-gnueabihf/libgcc_s.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libbrotlicommon.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/liblzma.so.5 ./lib/
cp /lib/arm-linux-gnueabihf/libzstd.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/liblz4.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libgcrypt.so.20 ./lib/
cp /lib/arm-linux-gnueabihf/libnsl.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libFLAC.so.8 ./lib/
cp /lib/arm-linux-gnueabihf/libvorbis.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libvorbisenc.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libopus.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libogg.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libnsl.so.1 ./lib/
cp /lib/arm-linux-gnueabihf/libresolv.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libbsd.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libgpg-error.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libtirpc.so.3 ./lib/
cp /lib/arm-linux-gnueabihf/libmd.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libkrb5.so.3 ./lib/
cp /lib/arm-linux-gnueabihf/libk5crypto.so.3 ./lib/
cp /lib/arm-linux-gnueabihf/libcom_err.so.2 ./lib/
cp /lib/arm-linux-gnueabihf/libkrb5support.so.0 ./lib/
cp /lib/arm-linux-gnueabihf/libkeyutils.so.1 ./lib/

